version: "2.1"

networks:
  webnetwork:

services:
  redis:
    image: redis:alpine
    networks:
      - webnetwork
    restart: always
  postgres:
    image: postgres:9.6
    networks:
      - webnetwork
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: v_database
    restart: always
  server:
    image: stream-server:0.0.1
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    networks:
      - webnetwork
    environment:
      DB_HOST: postgres
      REDIS_HOST: redis
      CRAPING_HOST: craping-server
    restart: on-failure
  craping-server:
    networks:
      - webnetwork
    image: craping-service:0.0.1
    volumes:
      - ./craping-server:/usr/src/app
    ports:
      - "5000:5000"
    restart: on-failure
