version: 1
networks:
  testnetwork:
services:
  redis:
    image: redis:alpine
    container_name: cache
    expose:
      - 6379
    volumes:
      - /tmp/redis:/data
    restart: always
  postgres:
    image: postgres:9.6
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - /tmp/postgres:/var/lib/postgresql/data
    restart: always
  server:
    image: api-server:0.0.1
    volumes:
      - ${PWD}/setting.json:/user/src/app
    ports:
      - "80:4000"
    restart: on-failure
