export const BOLD = 'bold'
export const ITALIC = 'italic'
export const HIGHLIGHT = 'highlight'
export const UNDERLINE = 'underline'

export const TITLE = 'title'
export const MATH = 'math'
export const CODE = 'code'
export const CODE_LINE = 'code_line'
export const ORDERED_LIST = 'ordered_list'
export const UNORDERED_LIST = 'unordered_list'
export const LIST_ITEM = 'list_item'
export const PARAGRAPH = 'paragraph'
export const TABLE = 'table'
export const TABLE_ROW = 'table_row'
export const TABLE_CELL = 'table_cell'
export const LINK_BLOCK = 'link_block'